### ISSUE TITLE
Artefact viewer update

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#100]

**Comment by writerly03** [comment]
- [ ] [refresh artefact metadata viewer](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=466%3A7988&mode=design&t=XRrhmzFPYXwRtzKh-1)
- [ ] Add tooltips to the metadata viewer
- [ ] add 'exit artefact' navigation in upper right
- [ ] [implement nested replies](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=407%3A5353&mode=design&t=XRrhmzFPYXwRtzKh-1)

**Comment by tripledoublev** [comment]
@luluissaa to update the exit artefact button

**Comment by luluissaa** [comment]
@luluissaa design interaction for opening and closing tooltip

**Comment by tripledoublev** [comment]
[Request to save in Figma](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=420-3167&mode=dev)

**Comment by luluissaa** [comment]
@luluissaa design ui for "inventory view" for placing artefact from studio to commons

**Comment by writerly03** [comment]
Closing because all outstanding tasks have been moved to new issues.
