### ISSUE TITLE
Server customization pages update

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#101]

**Comment by writerly03** [comment]
- [ ] Add server customization button

**Comment by writerly03** [comment]
- [ ] update [server setting ](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=1367%3A20184&mode=design&t=kI3zBzywXUWQWFbB-1)page layout

**Comment by writerly03** [comment]
- [ ] update[ manage alias](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=1367%3A20278&mode=design&t=kI3zBzywXUWQWFbB-1) page layout

**Comment by tripledoublev** [comment]
Closing the issue.
Created #105 for the outstanding task
