### ISSUE TITLE
Create feature to add additionnal pages/grid in the studio

### ISSUE THREAD

**Issue by tripledoublev** [hyphacoop/restructuring-futures#107]

**Comment by tripledoublev** [comment]
Created a new component that allows to create new pages in the studio 2f59dd0001471069cf129daf901750bf08a829fe
I then integrated it into the studio's GridView 45b50b484a9ddadfbab95aaaa920830ee0c232db

Next step is to [define how a user selects a page](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU?node-id=1375:5514&mode=dev#509116719) before uploading to it.

**Comment by tripledoublev** [comment]
Created a dropdown to select the page before the grid location is selected. 60ff5a8ffc9903798ab857417f6c007559e67f7b

![Image](https://github.com/hyphacoop/restructuring-futures/assets/631268/75ae6644-3071-4e4e-a945-cb70c2d286be)

**Comment by writerly03** [comment]
No feedback given on this, so closing the issue
