### ISSUE TITLE
General touch-ups and fixes

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#110]

**Comment by tripledoublev** [comment]
- Fixed the calculation that used to incorrectly count the number of artefact in each phase 0b1fb7ca918ea1fccdbdc420f213590a49da1700
- Adjusted UI layout for better responsiveness  51a5bfab840e9303db474db341c188e215e6ee04
- Refactor attachment handling and enhance UI in GetAttachment.svelte cdf20d745c92fbb99bfd080355586cf61a347ab2
- Fixed replies error where replies would show on the wrong artefact a36be3fcd75cf217a95ff09e282ee2d1bcb6c0b1
- Corrected server count coundition ec5975b323cf38175af81f22481336cd378e9a1d
- Adjust grid layout widths 31a823b67b4214a9fcd78185da36ca60711e21f7
- Bump earthstar to latest version 85997b426eadfd700f8a44aa7e0189ea05e1302b
- Integrated easy to change share keypairs f2320b7ce0748124486b3da96871f76958e9363c 32494f08237c5a2c7f3409163cf4f8b9723d36d0
- Server list is now automatically updated after add/remove action d2ea947b221d3ae7faf15a67280e2313dffe66a2
- Add script for quick keypair generation 7f958bf452f17d0161677fce02e9616be01cd876
 - Add Switch share function that automatically fetches from the studio after entering the portal 05ed19bf018298d9a9cb14da4d72c99abee83daf
