### ISSUE TITLE
the close button is not showing and the panel is half cropped

### ISSUE THREAD

**Issue by luluissaa** [hyphacoop/restructuring-futures#115]
**Describe the bug**
the close button is not showing and the panel is half cropped

**Steps to reproduce**
<img width="1512" alt="image" src="https://github.com/hyphacoop/restructuring-futures/assets/16890777/233e98ef-82b8-4fd9-a999-852c26f2ed19">

**Comment by tripledoublev** [comment]
- 6efcee2de90394a8b12b4105c8ccba2899804961
- efe4c95104013c75aedf00df60a0a0fbf7889f8a
