### ISSUE TITLE
audio playback on different browsers not working

### ISSUE THREAD

**Issue by luluissaa** [hyphacoop/restructuring-futures#120]
**Describe the bug**

**Steps to reproduce**
1. Go to 'JERRY IS AWESOME'
2. Click on the audio reply
3. sees an error because the audio file created in another browser might be incompatible????

**Expected behavior**
audio plays across browsers

**Screenshots**

**Environment (please complete the following information):**
- OS: [e.g. iOS] Mac
- Browser [e.g. chrome, safari] audio recorded using Firefox, won't playback when switching to safari

**Additional context**

**Comment by tripledoublev** [comment]
This bug is also referenced in #118

**Comment by tripledoublev** [comment]
I think I fixed it.
I dived into the cross-browser compatible audio formats waters and emerged with the webm format.
Ive deployed the edit. Will do further testing and commit the changes.
The fix will not apply to previously recorded voice note but all future audio recording should be playable across browsers.
