### ISSUE TITLE
Design & UI tweaks

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#125]
Small edits to the UI.

From our Sept 13 meeting:

Initial app page (rat page)
- [x] Add help text to the main page to let people know that they have to create an identity

- [x] Move studio portal to the top of page (_or add 'speed run option?_)
- [x] Change name of "server customization" button to something that reflects workspace settings as well; current name is misleading

Workspace settings page:
- [ ] Change the name of “add a share” to “add a studio”
- [x] Change error message from undefined to “this studio creation was invalid”
- [x] - [ ] When removing shares - need to generate an error message in the window or prompt people to type in the name of the share
- [ ] Change 'share' mentions to studios OR commons (as makes sense) throughout the app

Studios:
- [x] If no artefacts in the studio, change “looking” to “there are no artefacts”

**Comment by tripledoublev** [comment]
instead of replacing `share` with `studio` or` commons`, i went with the word workspace.
the reasoning is that some of these interactions are based on user input.
` generate new workspace` works no matter if the user is about to create a studio or a new commons.
