### ISSUE TITLE
Establish co-working days and tools

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#20]
Luisa and Vincent to coordinate how/when they will co-work for the first sprint

**Comment by tripledoublev** [comment]
We have planned for two co-working days.

- Tuesday afternoon
-  Thursday morning

The Tuesday session follows UKAI's internal meeting. This would be a good opportunity to share discussion items that came up during the morning's meeting.

The session on Thursday is to follow-up on our _RSF_ Wednesday meeting and address any issues that came up earlier in the week.

As for tools, I think we will see the type of tools evolve with the project. 

- Google Docs for text
- tldraw for visuals. 

As prototypes are built, we could use their features to test and exchange on what does and does not work.

**Comment by tripledoublev** [comment]
Co-working days are set:
-Tuesdays 1pm
-Thursdays 10am
