### ISSUE TITLE
Finalize features list

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#21]
Running list of features requested for the RSF project. Not all features listed here will be prioritized.

**Comment by writerly03** [comment]
# Features

- customizable avatars
- anonymous and pseudonymous avatars
- composable interior spaces
- decay/expiry of artefacts
- AI oracle
- customizable file sharing
- record and share voice notes
- access to underlying infrastructure/ technology
- built for offline/async use first (mobile second; desktop third?)
- chat or note passing
-

**Comment by writerly03** [comment]
Here is the shortlist of features that we feel are achievable within the budget and time frame:


1. File sharing
3. Voice notes
4. Notes (async messages)
5. Map and navigation
6. Drag and drop
7. Bulletin board
8. Calendar
9. Network status
10. Time stamped interactions
11. Anonymous and pseudonymous identities
12. 2-way chat
13. Decay and reification of artifacts
14. Customizable avatars
15. Composable interiors  

Stretch feature: artefact clustering/monument building

Not doing: encryption outside of what is native to the protocols; trailing or shadowing ppl

**Comment by writerly03** [comment]
@tripledoublev can you review the above list and ensure this reflects our discussion. I also need some help with clustering them; they appear here as discrete items but many are linked/build on each other and will need to be grouped together within the sprints

**Comment by tripledoublev** [comment]
Hi @writerly03,
I've regrouped related features that build on each other. 
 
- File sharing
   * Voice notes
   * Other file formats
   * Drag and drop    

- Notes (async messages)
   * 2-way chat
   * Bulletin board
   * Calendar

- Time stamped interactions
   * Adding and removing time before deletion (Decay and reification of artifacts)

- Anonymous and pseudonymous identities
   * Customizable avatars

- Composable interiors

- Map and navigation

- Network status

**Comment by tripledoublev** [comment]
As uploading and extending the lifespan of an ephemeral document requires an identity, I have done some work on integrating keypairs in the app.

Identities are currently generated automatically on each visit which allows for quick and easy testing. 
I also provided a download button so Users can store their keypair for future use.
For more information on Identity related features, see Issue #55

**Comment by writerly03** [comment]
Add gift exchange to this list
