### ISSUE TITLE
Share/develop mood boards/visual guide for look of site

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#25]

**Comment by tripledoublev** [comment]
Here is a [Figma board](https://www.figma.com/file/wy7hjH2Gmwe0KJsKIpebNG/RSF?node-id=0%3A1&t=J8aCxkOCocIv5X79-0) that was shared today during our co-work session

**Comment by writerly03** [comment]
Figma mood board https://www.figma.com/file/aW4n9QVmae8xdHldDtCBbl/RSF-mood-board?node-id=0:1&t=HJHMtNS5BA2QuzaI-0
