### ISSUE TITLE
Feature: time stamping

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#29]

**Comment by writerly03** [comment]
Note: changed the issues name from object decay to time stamp; object decay will be the visual representation of the time stamp and time passing

**Comment by writerly03** [comment]
Sprint 2

to do:  
- connect time stamp to file sharing
- test out the applicability of making document disappear and reappear

**Comment by writerly03** [comment]
To do:

- what is the default lifespan of the documents that appear in the commons?
- need to clarify how the syncing process works with multiple studios (move to studio issue)
- how does permissioning work with multiple studios? (new permissioning issue)
- how can we make permissioning more granular
- 
-

**Comment by tripledoublev** [comment]
In the studio, files/artifact are permanent yet they contain the history of their ephemeral counterpart found in the commons.
This means that ephemeral interactions such as extending the lifespan of a file are logged into the non-ephemeral archived version of that file in the studio. This feature's aim was to validate that interactions in the commons can be recorded in the studio and preserved even after the artifact has disappeared from the commons.

**Comment by tripledoublev** [comment]
View of the current Ephemeral component

The ⌛ hourglass emoji reveals the buttons that interact with the _deleteAfter_ property.

➕ pushes the property back and extends the ephemeral document's availability before its deletion.
➖ shortens the ephemeral document's time until deletion. Removing time from the the _deleteAfter_ property.

🗑️ deletes the file by setting the deleteAfter property in the very near future.

A counter is updated displaying the time until deletion


![Image View of the Ephemeral component
](https://user-images.githubusercontent.com/631268/221034959-4e2b0fdc-70f8-47c0-9f68-5cf45c08b801.png)

**Comment by tripledoublev** [comment]
The interactions involving the _timestamp_ and _deleteAfter_ properties can currently be found in the Details Component

![Image](https://user-images.githubusercontent.com/631268/221037710-0062b176-53cd-4d86-bedc-10777bca83b7.png)

**Comment by tripledoublev** [comment]
A question that remains is what would be an adequate visualization of time stamping and ephemerality in this browser environment.
The [ephemeral chat prototype](https://hyphacoop.github.io/restructuring-futures/web/02_time-experiment/) explored the possibility to link transparency to the time left until deletion with the CSS _background-color_ property.


![Image of the time experiment; chat prototype](https://user-images.githubusercontent.com/631268/221044321-8b8e4b37-b8f6-43b2-825d-a69206249ccf.png)


This type of mapping values could be explored further with other CSS properties such as dimensions, border, colors, margins, padding and many more.
A more specific question would be if we want to see documents fading away as they are about to disappear or would we prefer see them expand and grow like the[ Fungal font](https://velvetyne.fr/fonts/fungal/).

**Comment by writerly03** [comment]
@luluissaa @Will-Sin would love to see some ideas about how the time decay can be visually represented; the current background colour (which I know is a placeholder) isn't intuitive
