### ISSUE TITLE
Feature: voice notes

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#33]

**Comment by writerly03** [comment]
Sprint Notes

- - voice notes are file attachments
- voice notes worked, then broke with the Earthstar upgrade
- there was a patch that fixed this
- can extend the lifetime of a document or attachment; this was successful quickly
-

**Comment by tripledoublev** [comment]
I isolated the _voice notes_ feature on [this page](https://hyphacoop.github.io/restructuring-futures/web/04_voice-notes/).
As is the case with other attachments such as images, the functionality works locally but the replica runs into syncing issues. 
Besides looking into the instantiation of adequate replica drivers for data storage and retrieval, I will be investigating into proper [attachment ingestion](https://earthstar-project.org/specs/data-spec-es5#ingesting-attachments)
