### ISSUE TITLE
p2p protocol/tool assessment for features

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#44]
List from Hypha:

https://docs.storj.io/dcs/how-tos/host-a-static-website/host-a-static-website-with-the-cli-and-linksharing-service
https://sher.geutstudio.com/
https://p2panda.org/
https://fission.codes/

**Comment by tripledoublev** [comment]
Let's add [Hypercore/Holepunch](https://docs.holepunch.to/) and [IPFS](https://docs.ipfs.tech/) to that list even if I will be focusing on [Earthstar](https://earthstar-project.org/) for the time being.

**Comment by tripledoublev** [comment]
Closing this as we will be focusing on Earthstar.
