### ISSUE TITLE
Explore melon.js

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#48]
Carefully look through the crispy couscous repo and determine how we can re-purpose elements of spatiality

**Comment by tripledoublev** [comment]
I found the [images for the map](https://github.com/hyphacoop/crispy-couscous/tree/main/src/data/img/map)
I will keep exploring the repo to determine how its spatial component can be re-purposed.
I am particularly curious if it was mobile compatible and if so, how it dealt with movement for users on such devices.

**Comment by writerly03** [comment]
Here is the link to the actual prototype: https://hyphacoop.github.io/crispy-couscous/
