### ISSUE TITLE
Customizable avatar feature wireframe

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#62]
Create higher fidelity wireframe showing interactions/user journey with this feature.

This should also include any required tooltips or labels that you want to see implemented.

**Comment by luluissaa** [comment]
not an avatar but a log of attributes to the ID: ie, files uploaded, hidden files, requests/permissions etc.

**Comment by tripledoublev** [comment]
@luluissaa does this mean we no longer want to have customizable/extendable identities such as a longer alias and about me section?
examples of such info can be found in the **[data format](https://github.com/earthstar-project/earthstar/wiki/Standard-paths-and-data-formats-used-by-apps#about-author-profile-info)** and **[profile info](https://earthstar-project.org/specs/data-spec-es5#identity-display-names-and-profile-info)** specs

It would be useful to define if this is one **and** the other or if the attributes log you define replaces the identity profile.

From the log of attributes list, here are a few questions that could help define the features wireframe.

- files uploaded:
     - does this include ephemeral files as well?   
     - does this also include replies?
     - i imagine this would be specific to the current share and not include other shares. is this correct?

- hidden files:
    - is this for the user to keep track of the files they did hide?
    - if so, this would be a way to *unhide*
    - what else would this hidden files list be useful for?
 
 - requests/permissions:
     - this is most likely where you accept or deny requests and give permissions
     - this would be where you find active requests but should it also show a log of all past requests ?
     -  what are the possible reactions here? 
         - accept
         - deny
         - other?

**Comment by writerly03** [comment]
This is crossed off the design checklist. Need a response to Vincent's questions above plz so we can close or merge this issue
