### ISSUE TITLE
Resolve properties of artefacts

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#66]
Adjustment of artefact features to align with desired outcomes.

- who can delete an artefact?
- can ephemeral document’s lifespan be extended, reduced?
- what other properties do you want to see represented in this iteration?
- Anything else that should be captured re: artefacts

**Comment by writerly03** [comment]
- who can delete? original poster can delete; anyone else can hide from their view

- - ephemeral doc lifespan: Extension from request of sharing, gifting, important to emphasize that these actions don't need to be so pragmatic. Instead of being a direct interactions.
-  Request to save/connect (like a pin in pinterest) + consequence of adding life span to an artefact
Ability to un-connect and revert the added lifespan
Request to hide from view + consequence of taking lifespan away from an artefact
Ability to un-hide and revert the subtracted lifespan

**Comment by tripledoublev** [comment]
Created #94 for myself to investigate hiding artifacts
