### ISSUE TITLE
Set up Earthstar on a Raspberry Pi

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#71]

**Comment by tripledoublev** [comment]
This morning, I followed the tutorial found on [this page](https://earthstar-project.org/tutorials/run-a-server)

[This is the version of Deno](https://github.com/LukeChannings/deno-arm64) that needs to be installed on a raspberry Pi

More documentation to come

**Comment by tripledoublev** [comment]
I have added the necessary files to the repository in order to run the earthstar server locally
https://github.com/hyphacoop/restructuring-futures/blob/main/server/README.md
