### ISSUE TITLE
Map icons to file types for image and text

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#82]

**Comment by tripledoublev** [comment]
Depends on #83

**Comment by writerly03** [comment]
Icon sets is here @tripledoublev https://www.dropbox.com/sh/ypk6k6tege37xey/AADWeqs6Fv3xtn91VtsaT8rba?dl=0

**Comment by writerly03** [comment]
Mapping for icons is here: https://docs.google.com/spreadsheets/d/1_vp039Szmi-Yu_Mvg9jatbVuIhibdJAcZAyerHKnSyc/edit#gid=0

**Comment by tripledoublev** [comment]
- 37adb9082ca355d828476e86c04d66ae2ad83307
- 72cafabc52d532810ca366f886a5bfcce56912fd
- c4eff8379ee88206e8f84d1aa3f4b782fd5c5785
