### ISSUE TITLE
Finish icon sets

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#83]
Icons for sound, video and other need to be completed: https://docs.google.com/spreadsheets/d/1_vp039Szmi-Yu_Mvg9jatbVuIhibdJAcZAyerHKnSyc/edit#gid=0

**Comment by luluissaa** [comment]
@Will-Sin @tripledoublev any thoughts on making the icons SVG? I'm playing around with the decay details and thought we can play with the saturation values in HSLA to give each phase the illusion of fading away/old

**Comment by luluissaa** [comment]
for example: 
blur radius for icons doubles each phase
phase 1: no blur |  hsla(191, 100%, 18%, 1)
phase 2: 25px | hsla(191, 100%, 18%, 1)
phase 3:  50px | hsla(191, 50%, 18%, 1)
phase 4: 100px | hsla(191, 25%, 18%, 1)

**Comment by tripledoublev** [comment]
Svg is indeed a good option for programmatically controlling images.
If we stick with other image formats, there is the option of using CSS transform filters.

**Comment by tripledoublev** [comment]
Icons can be seen on [this spreadsheet](https://docs.google.com/spreadsheets/d/1_vp039Szmi-Yu_Mvg9jatbVuIhibdJAcZAyerHKnSyc/edit#gid=0)

**Comment by tripledoublev** [comment]
Added the new icons:

- 37adb9082ca355d828476e86c04d66ae2ad83307
- 72cafabc52d532810ca366f886a5bfcce56912fd
- c4eff8379ee88206e8f84d1aa3f4b782fd5c5785
