### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#85]
Review the section of the Figma that deals with replies; implement the code listed here: https://codepen.io/will-sin/pen/KKrpOeb

(except that it's not animated)

**Comment by tripledoublev** [comment]
To be Applied on 
Replies appear visually in the grid view

**Comment by luluissaa** [comment]
detail the reply UI and how the thread can be interacted and viewed

**Comment by tripledoublev** [comment]
I applied the visual representation of the Replies on the Grid View e2d837bc0221ddba642ad88d3192e461f6e4c3a0
It looks great.
There might have a need for some layout tweaks in terms of sizing and location but the basic functionality is in.
Note that the orbiting is currently animated. The movement might be distracting but I thought it was worth it to integrate it as it was in the code snippet shared above. It is really easy to remove so please let me know if this is something that should be static.


![Image](https://github.com/hyphacoop/restructuring-futures/assets/631268/80bbfc34-f461-4edd-9595-af3ecc798794)

**Comment by tripledoublev** [comment]
Replies are now loaded on mount b2186ef5e40db463a9dcf0de35f92a402e29f70b
Closing this issue. Let's create a new one for reply design changes if necessary.
