### ISSUE TITLE
Mobile grid

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#86]
Use Figma to develop a mobile-friendly grid

**Comment by tripledoublev** [comment]
I have adapted the grid view based on the figma layout ab3e92299086aff4c8e59586162da8d6c794c322
The grid used for uploading artifacts will need to be reworked to allow for scrolling as it requires much more horizontal space than the previous design 91539c26c37b9d4c3c94a8c8a08b4c95447966b7
I will need to do test to make sure the scrolling option does not interfere with clicking on the grid's cell

**Comment by tripledoublev** [comment]
Instead of maintaining the aspect ratio, let`s number the cell of the mobile grid.

**Comment by luluissaa** [comment]
in the upload view, can we add a colour or some indication in cells already with artefacts?

**Comment by tripledoublev** [comment]
For mobile, filter out empty cells (cell without artifacts) and only display the ones with content as a way to reduce unnecessary scrolling.

**Comment by tripledoublev** [comment]
The mobile grid is now shortened by removing empty cells. b36acead1a0b8dc100bca83e2426e5c32f653823
The upload grid now has the cell x y coordinates for easier position tracking. ca3e978dbeafec9dbb56fa649784885688556e47
