### ISSUE TITLE
Refine ephemerality design

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#87]
The current ephemerality design is confusing to users. Please suggest some design refinements that stays true to the concept while also clarifying for users.

**Comment by tripledoublev** [comment]
Currently:
- Icons
- Colors
- Blurry effect

**Comment by luluissaa** [comment]
@luluissaa 

Icons of different phases
Background colours

UI and way finding for explaining what phase and level of interactivity an artifact has

**Comment by writerly03** [comment]
- [ ][ implement these behaviours](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=356%3A26&mode=design&t=CHrC5L8hzASDrqEH-1) for icons/artefacts that are interactive 
- [ ] - [ ] update icons to SVG and implement the following [colour saturation changes](https://www.figma.com/file/DDLsuwTdBZ4MsF9aorBjtU/RSF-Workspace?type=design&node-id=356%3A26&mode=design&t=CHrC5L8hzASDrqEH-1)

**Comment by writerly03** [comment]
icon phase names: spore, emergent, epic, fizz
