### ISSUE TITLE
Download function for post-event scenario

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/restructuring-futures#88]
@luluissaa please provide some specs outlining what you want this feature to look like and do. The development of this is dependant on getting this; otherwise we can move to backlog.

**Comment by luluissaa** [comment]
The thinking is that if someone has already been a host for the studio's share(s) they will have access to that information already and will be able to use the archive feature

**Comment by tripledoublev** [comment]
Leave the button.
Move it the tot he settings.
Create counter to keep track of usage
